apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-green
spec:
  selector:
    matchLabels:
      type: backend
      deployment: green
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
        deployment: green
    spec:
      containers:
        - name: backend-green
          image: 706com/backend:latest
          envFrom:
            - secretRef:
                name: sec-backend
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/nginx/comegongbang
      volumes:
        - name: secret-volume
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: certificate.crt
              - key: tls.key
                path: private.key
      terminationGracePeriodSeconds: 0
