apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-green
spec:
  selector:
    matchLabels:
      type: backend
      deployment: green
  replicas: 2
  strategy:
    type: RollingUpdate
#  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
        deployment: green
    spec:
      containers:
        - name: backend-green
          image: 706com/backend:latest
          ports:
            - containerPort: 8080
