apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
spec:
  selector:
    matchLabels:
      type: backend
      deployment: blue
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
        deployment: blue
    spec:
      containers:
        - name: backend-blue
          image: 706com/backend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/nginx/comegongbang
      volumes:
        - name: secret-volume
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: certificate.crt
              - key: tls.key
                path: private.key
      terminationGracePeriodSeconds: 0
