server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://mariadb-master-svc2:3306/CGB
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  #show '?' in sql in console