apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-blue
spec:
  selector:
    matchLabels:
      type: frontend
      deployment: blue
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
        deployment: blue
    spec:
      containers:
        - name: frontend-blue
          image: nginx:alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: 443
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              scheme: HTTPS  # HTTPS 스키마로 변경
              path: /
              port: 443      # 포트를 443으로 변경
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/nginx/comegongbang
            - name: html-volume  # HTML 파일을 위한 볼륨 추가
              mountPath: /usr/share/nginx/html  # Nginx의 기본 HTML 경로에 마운트
      volumes:
        - name: secret-volume
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: certificate.crt
              - key: tls.key
                path: private.key
        - name: html-volume  # HTML 파일을 위한 볼륨 추가
          emptyDir: { }  # 파드가 삭제될 때 데이터가 사라지는 임시 볼륨
      terminationGracePeriodSeconds: 0
