name: Deploy to AWS EC2

# 배포 조건
# 1) backend/develop -> develop MERGE
# 2) Labeling
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  deploy:
    if: github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'backend') &&
      contains(github.event.pull_request.labels.*.name, 'operation')
    runs-on: ubuntu-latest

    steps:
      # 소스 코드를 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v2

      # JDK 설정
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant permission
        run: chmod +x ./gradlew
        working-directory: ./backend

      # backend 폴더로 이동해 Spring Boot 애플리케이션을 빌드
      - name: Build project in backend folder
        run: ./gradlew bootJar
        working-directory: ./backend
        env: # 환경 변수를 설정
          AES_ALGORITHM: ${{ secrets.AES_ALGORITHM }}
          AES_SECRET_KEY: ${{ secrets.AES_SECRET_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DDL_TYPE: ${{ secrets.DDL_TYPE }}
          ES_HOST: ${{ secrets.ES_HOST }}
          ES_PORT: ${{ secrets.ES_PORT }}
          ES_URL: ${{ secrets.ES_URL }}
          FIXED_DELAY: ${{ secrets.FIXED_DELAY }}
          FRONT_REDIRECT_URL: ${{ secrets.FRONT_REDIRECT_URL }}
          IMP_API_KEY: ${{ secrets.IMP_API_KEY }}
          IMP_SECRET_KEY: ${{ secrets.IMP_SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          KAKAO_REDIRECT_URL: ${{ secrets.KAKAO_REDIRECT_URL }}
          KAKAO_REST_API: ${{ secrets.KAKAO_REST_API }}
          MAX_ACTIVE: ${{ secrets.MAX_ACTIVE }}
          PORT: ${{ secrets.PORT }}
          QUEUE_NECESSARY: ${{ secrets.QUEUE_NECESSARY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          WAITING_QUEUE_SCHEDULER: ${{ secrets.WAITING_QUEUE_SCHEDULER }}

      # 빌드 파일을 EC2 인스턴스로 전송
      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.0.5
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_BACK }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/action/app.jar"

      # EC2 인스턴스에서 애플리케이션 실행
      - name: Run application on EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 8080 포트에서 실행 중인 기존 프로세스 종료
            if lsof -i:8080 -t >/dev/null; then
              kill -9 $(lsof -i:8080 -t)
            fi
            # 새로운 애플리케이션 실행
            nohup java -jar /home/ubuntu/action/app.jar > /home/ubuntu/action/app.log 2>&1 &